version: '3.9'

services:
    pgsql:
        image: postgres:17.0-alpine3.20
        volumes:
            - ./db_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: test
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
        networks:
            - pgsql-net
    
    adminer:
        image: adminer:latest
        restart: always
        ports:
            - 8080:8080
        depends_on: 
            - pgsql
        networks:
            - pgsql-net

networks:
    pgsql-net: